#ifndef __SparkCalc__
#define __SparkCalc__

/**
@file SparkCalc.h
Subclass of Spark, which is generated by wxFormBuilder.
*/

#include "wx/wxprec.h"
#include "SparkUI.h"
#include "wx/wupdlock.h"
#include "operation-tree/OperationTree.hpp"
#ifndef WX_PRECOMP
    #include "wx/wx.h"
#endif

//// end generated include

/** Implementing Spark */
class SparkCalc : public Spark
{
	public:
		/* Constructor */
		SparkCalc( wxWindow* parent );
        
        /**
             An event that's called whenever the Quit/Exit button is clicked in the menu bar.
             @param event the event triggered by the button click
         */
        void OnQuit(wxCommandEvent& event);
    
        /**
            An event that's called whenever the About button is clicked in the menu bar.
            @param event the event triggered by the button click
         */
        void OnAbout(wxCommandEvent& event);
    
        void OnCut(wxCommandEvent& event);
        void OnCopy(wxCommandEvent& event);
        void OnPaste(wxCommandEvent& event);
        void OnUndo(wxCommandEvent& event);
        void OnRedo(wxCommandEvent& event);
        void OnSelectAll(wxCommandEvent& event);
    
        /**
            An event that's called whenever text is input into the math_input wxRichTextCtrl.
            @param event the event
         */
        void math_input_evt(wxCommandEvent& event);
    
        /**
            A method that syncs the scroll height between math_input and math_output, while also
            setting math_scrollbar to the correct scroll level.
         */
        void sync_all_scrollbars();
    
        /**
            An event that's called whenever any key is pressed. The event looks for any nagivation key inputs
            or arrow key inputs, and calls sync_all_scrollbars() in the event any of those keys were pressed.
         */
        void math_sync_scrollbar( wxKeyEvent& event );
    
        /**
            An even that's called whenever the user clicks or drags the math_scrollbar. It appropriately syncs
            the scroll level of the scrollbar with the math_input and math_output wxRichTextCtrls.
         */
        void math_scroll_evt( wxScrollEvent& event );
    
        /**
            An event that's called whenever the scroll wheel of the mouse scrollwheel scrolls up. It appropriately applies all
            necessary changes to math_input/math_output/math_scrollbar to keep them in sync.
         */
        void math_scroll_up_evt( wxScrollEvent& event );
    
        /**
           An event that's called whenever the scroll wheel of the mouse scrollwheel scrolls down. It appropriately applies all
           necessary changes to math_input/math_output/math_scrollbar to keep them in sync.
        */
        void math_scroll_down_evt( wxScrollEvent& event );

    private:
        /** The default text style for the math_input wxRichTextCtrl. */
        wxRichTextAttr Standard_Input_Style;
        /** The text color used whenever a variable name is highlighted in math_input. */
        wxColour Input_Variable_Color;
        /** The default text color used by math_input. */
        wxColour Default_Input_Color;
        /** The color of all text in math_output */
        wxColour Answer_Color;
        /** The text color used by math/trig functions */
        wxColour Function_Color;
        wxDECLARE_EVENT_TABLE();
        
};

enum
{
    // menu items
    Spark_Quit = wxID_EXIT,

    // it is important for the id corresponding to the "About" command to have
    // this standard value as otherwise it won't be handled properly under Mac
    // (where it is special and put into the "Apple" menu)
    Spark_About = wxID_ABOUT
};

#endif // __SparkCalc__
